export { default as EffectMenu } from './Effect'
export { default as FontMenu } from './Font'
export { default as TextColorMenu } from './TextColor'
export { default as BackgroundColorMenu } from './BackgroundColor'
export { default as BackgroundThemeMenu } from './BackgroundTheme'
